# Generated by Django 5.0.3 on 2024-03-25 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='salary',
        ),
    ]
